# Generated by Django 5.0.1 on 2025-10-17 22:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this patient",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "family_name",
                    models.CharField(help_text="Family name (surname)", max_length=255),
                ),
                (
                    "given_name",
                    models.CharField(
                        help_text="Given name (first name)", max_length=255
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Middle name(s)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Administrative gender - male | female | other | unknown",
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField(help_text="Date of birth")),
                (
                    "address_line",
                    models.CharField(
                        blank=True,
                        help_text="Street address",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "address_state",
                    models.CharField(
                        blank=True,
                        help_text="State or province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "address_postal_code",
                    models.CharField(
                        blank=True, help_text="Postal code", max_length=20, null=True
                    ),
                ),
                (
                    "address_country",
                    models.CharField(
                        blank=True, help_text="Country", max_length=100, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address",
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=50, null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this patient's record is in active use",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Record last update timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family_name", "given_name"],
                        name="patients_pa_family__a96a9c_idx",
                    ),
                    models.Index(
                        fields=["birth_date"], name="patients_pa_birth_d_51eba5_idx"
                    ),
                    models.Index(fields=["email"], name="patients_pa_email_bb026d_idx"),
                ],
            },
        ),
    ]
