# Generated by Django 5.0.1 on 2025-10-18 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("practitioners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on-hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("entered-in-error", "Entered in Error"),
                            ("stopped", "Stopped"),
                            ("draft", "Draft"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal"),
                            ("plan", "Plan"),
                            ("order", "Order"),
                            ("original-order", "Original Order"),
                            ("reflex-order", "Reflex Order"),
                            ("filler-order", "Filler Order"),
                            ("instance-order", "Instance Order"),
                            ("option", "Option"),
                        ],
                        default="order",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("asap", "ASAP"),
                            ("stat", "STAT"),
                        ],
                        default="routine",
                        max_length=10,
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text="Name of the medication", max_length=500
                    ),
                ),
                (
                    "medication_code",
                    models.CharField(
                        blank=True,
                        help_text="Code identifying the medication (e.g., RxNorm, SNOMED)",
                        max_length=100,
                    ),
                ),
                (
                    "medication_form",
                    models.CharField(
                        blank=True,
                        help_text="Form of medication (e.g., tablet, capsule, liquid)",
                        max_length=200,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        help_text="Strength of medication (e.g., 500mg)",
                        max_length=100,
                    ),
                ),
                (
                    "dosage_text",
                    models.TextField(
                        blank=True, help_text="Free text dosage instructions"
                    ),
                ),
                (
                    "dosage_route",
                    models.CharField(
                        blank=True,
                        help_text="Route of administration (e.g., oral, IV)",
                        max_length=200,
                    ),
                ),
                (
                    "dosage_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Frequency of administration (e.g., twice daily, every 4 hours)",
                        max_length=200,
                    ),
                ),
                (
                    "dose_quantity",
                    models.CharField(
                        blank=True,
                        help_text="Amount of medication per dose (e.g., 1 tablet, 5 mL)",
                        max_length=100,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Amount to be dispensed", null=True
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit for quantity (e.g., tablets, mL, boxes)",
                        max_length=50,
                    ),
                ),
                (
                    "refills",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of refills authorized"
                    ),
                ),
                (
                    "dispense_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Expected days supply per dispense",
                        null=True,
                    ),
                ),
                (
                    "authored_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When prescription was initially written",
                    ),
                ),
                (
                    "validity_start",
                    models.DateField(
                        blank=True,
                        help_text="Start date of prescription validity",
                        null=True,
                    ),
                ),
                (
                    "validity_end",
                    models.DateField(
                        blank=True,
                        help_text="End date of prescription validity",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason or indication for prescription"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the prescription"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient for whom medication is prescribed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescriber",
                    models.ForeignKey(
                        help_text="Practitioner who prescribed the medication",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="practitioners.practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-authored_on"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="prescriptio_status_940ca9_idx"
                    ),
                    models.Index(
                        fields=["patient", "-authored_on"],
                        name="prescriptio_patient_1a3e4d_idx",
                    ),
                    models.Index(
                        fields=["prescriber", "-authored_on"],
                        name="prescriptio_prescri_96d19a_idx",
                    ),
                ],
            },
        ),
    ]
