---
# Redis role - Cache and Celery backend

- name: Install Redis
  apt:
    name:
      - redis-server
      - redis-tools
    state: present

- name: Configure Redis to bind to localhost
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 127.0.0.1 ::1'
    state: present
  notify: restart redis

- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes
