# Generated by Django 5.0.1 on 2025-10-18 15:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Unique invoice number", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("balanced", "Balanced"),
                            ("cancelled", "Cancelled"),
                            ("entered-in-error", "Entered in Error"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount before tax",
                        max_digits=10,
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount including tax",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax amount",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount already paid",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining balance",
                        max_digits=10,
                    ),
                ),
                (
                    "service_description",
                    models.TextField(help_text="Description of services provided"),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        help_text="Service code (CPT, HCPCS)",
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(help_text="Date invoice was issued")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                (
                    "service_date",
                    models.DateField(
                        blank=True, help_text="Date service was provided", null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Method of payment (credit card, insurance, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="Date payment was received", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional billing notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related appointment (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient being billed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="billing_inv_status_541249_idx"
                    ),
                    models.Index(
                        fields=["patient", "-issue_date"],
                        name="billing_inv_patient_3a0407_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="billing_inv_invoice_70511c_idx"
                    ),
                ],
            },
        ),
    ]
