# Generated by Django 5.0.1 on 2025-10-18 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("practitioners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("pending", "Pending"),
                            ("booked", "Booked"),
                            ("arrived", "Arrived"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("noshow", "No Show"),
                            ("entered-in-error", "Entered in Error"),
                            ("checked-in", "Checked In"),
                            ("waitlist", "Waitlist"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        help_text="Broad categorization of service",
                        max_length=200,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="Specific service to be performed",
                        max_length=200,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="Required practitioner specialty",
                        max_length=200,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        blank=True,
                        help_text="Style of appointment or patient",
                        max_length=100,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        help_text="Coded reason for appointment",
                        max_length=200,
                    ),
                ),
                (
                    "reason_description",
                    models.TextField(
                        blank=True, help_text="Detailed reason for appointment"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Priority (0=highest, higher number=lower priority)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description shown in appointment list",
                        max_length=500,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Additional comments about the appointment",
                    ),
                ),
                (
                    "patient_instruction",
                    models.TextField(
                        blank=True, help_text="Detailed instructions for the patient"
                    ),
                ),
                ("start", models.DateTimeField(help_text="When appointment starts")),
                ("end", models.DateTimeField(help_text="When appointment ends")),
                (
                    "minutes_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in minutes (can be estimate)",
                        null=True,
                    ),
                ),
                (
                    "patient_status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("tentative", "Tentative"),
                            ("needs-action", "Needs Action"),
                        ],
                        default="needs-action",
                        help_text="Patient participation status",
                        max_length=20,
                    ),
                ),
                (
                    "practitioner_status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("tentative", "Tentative"),
                            ("needs-action", "Needs Action"),
                        ],
                        default="needs-action",
                        help_text="Practitioner participation status",
                        max_length=20,
                    ),
                ),
                (
                    "practitioner_required",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("optional", "Optional"),
                            ("information-only", "Information Only"),
                        ],
                        default="required",
                        help_text="Whether practitioner is required",
                        max_length=20,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When appointment was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient involved in appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        help_text="Practitioner involved in appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="practitioners.practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-start"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                    models.Index(
                        fields=["patient", "start"],
                        name="appointment_patient_de3304_idx",
                    ),
                    models.Index(
                        fields=["practitioner", "start"],
                        name="appointment_practit_3da5f7_idx",
                    ),
                    models.Index(
                        fields=["start", "end"], name="appointment_start_0b4521_idx"
                    ),
                ],
            },
        ),
    ]
