# Generated by Django 5.0.1 on 2025-10-19 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        default="Healthcare Clinic",
                        help_text="Name of the clinic or healthcare organization",
                        max_length=255,
                    ),
                ),
                (
                    "clinic_address",
                    models.TextField(
                        blank=True, help_text="Full address of the clinic"
                    ),
                ),
                (
                    "clinic_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=50,
                    ),
                ),
                (
                    "clinic_email",
                    models.EmailField(
                        blank=True, help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "clinic_website",
                    models.URLField(blank=True, help_text="Clinic website URL"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Clinic logo for reports and documents",
                        null=True,
                        upload_to="clinic/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Primary brand color (hex format, e.g., #3B82F6)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#10B981",
                        help_text="Secondary brand color (hex format, e.g., #10B981)",
                        max_length=7,
                    ),
                ),
                (
                    "report_header_text",
                    models.TextField(
                        blank=True, help_text="Custom header text for reports"
                    ),
                ),
                (
                    "report_footer_text",
                    models.TextField(
                        blank=True,
                        default="© 2025 Healthcare Patient Management. All rights reserved.",
                        help_text="Custom footer text for reports",
                    ),
                ),
                (
                    "include_logo_in_reports",
                    models.BooleanField(
                        default=True,
                        help_text="Include clinic logo in generated reports",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinic Settings",
                "verbose_name_plural": "Clinic Settings",
            },
        ),
    ]
