---
# PostgreSQL role - Database installation and configuration

- name: Add PostgreSQL APT repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg

- name: Install PostgreSQL 16
  apt:
    name:
      - postgresql-16
      - postgresql-contrib-16
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is started and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create application database
  postgresql_db:
    name: "{{ db_name }}"
    state: present
  become_user: postgres

- name: Create application database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
  become_user: postgres

- name: Grant privileges to database user
  postgresql_privs:
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    privs: ALL
    type: database
    state: present
  become_user: postgres

- name: Grant schema privileges
  postgresql_privs:
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    objs: ALL_IN_SCHEMA
    privs: ALL
    type: table
    schema: public
  become_user: postgres

- name: Configure PostgreSQL authentication
  postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user }}"
    source: 127.0.0.1/32
    method: md5
  notify: restart postgresql

- name: Ensure PostgreSQL is listening on localhost
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = 'localhost'"
  notify: restart postgresql
